export default {
  '0fec2b6b': [() => import(/* webpackChunkName: '0fec2b6b' */ '/Users/kulakov/SynologyDrive-Documents/SynologyDrive-Documents/SynologyDrive/OpenSource/aivix-docs/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json'), '/Users/kulakov/SynologyDrive-Documents/SynologyDrive-Documents/SynologyDrive/OpenSource/aivix-docs/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/kulakov/SynologyDrive-Documents/SynologyDrive-Documents/SynologyDrive/OpenSource/aivix-docs/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1df93b7f': [() => import(/* webpackChunkName: '1df93b7f' */ '@site/src/pages/index.tsx'), '@site/src/pages/index.tsx', require.resolveWeak('@site/src/pages/index.tsx')],
  '45a5cd1f': [() => import(/* webpackChunkName: '45a5cd1f' */ '@site/docs/concepts.md'), '@site/docs/concepts.md', require.resolveWeak('@site/docs/concepts.md')],
  '5ddb69a7': [() => import(/* webpackChunkName: '5ddb69a7' */ '@site/docs/creating-first-agent.md'), '@site/docs/creating-first-agent.md', require.resolveWeak('@site/docs/creating-first-agent.md')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '6ede1544': [() => import(/* webpackChunkName: '6ede1544' */ '@site/docs/n8n-integration.md'), '@site/docs/n8n-integration.md', require.resolveWeak('@site/docs/n8n-integration.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'd589d3a7': [() => import(/* webpackChunkName: 'd589d3a7' */ '@site/docs/getting-started.md'), '@site/docs/getting-started.md', require.resolveWeak('@site/docs/getting-started.md')],
  'fe564277': [() => import(/* webpackChunkName: 'fe564277' */ '/Users/kulakov/SynologyDrive-Documents/SynologyDrive-Documents/SynologyDrive/OpenSource/aivix-docs/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/Users/kulakov/SynologyDrive-Documents/SynologyDrive-Documents/SynologyDrive/OpenSource/aivix-docs/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/kulakov/SynologyDrive-Documents/SynologyDrive-Documents/SynologyDrive/OpenSource/aivix-docs/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],};
